"""
Agent 6 — Notebook Writer (PySpark .ipynb generator).
Generates one Fabric PySpark notebook per domain cluster.
"""
from __future__ import annotations

import json
import logging
import re

from app.core.azure_openai import LLMResponse, llm_client
from app.prompts import (
    NOTEBOOK_DOMAIN_SPLITTER_SYSTEM_V1,
    NOTEBOOK_DOMAIN_SPLITTER_USER_V1,
    NOTEBOOK_WRITER_SYSTEM_V1,
    NOTEBOOK_WRITER_USER_V1,
)

logger = logging.getLogger(__name__)


def _make_empty_notebook(domain_name: str) -> dict:
    """Returns a minimal valid .ipynb structure."""
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "PySpark",
                "language": "python",
                "name": "synapse_pyspark",
            },
            "language_info": {"name": "python"},
        },
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"# {domain_name} Domain — Microsoft Fabric Lakehouse Load\n\nAuto-generated by Schema Transformer."],
            }
        ],
    }


class NotebookDomainSplitter:
    """Clusters star schema tables into logical business domains."""

    def split(self, schema_plan: dict) -> list[dict]:
        """Returns list of domain dicts: {domain_name, tables, description}."""
        user_prompt = NOTEBOOK_DOMAIN_SPLITTER_USER_V1.format(
            schema_plan_json=json.dumps(schema_plan, indent=2, default=str)
        )
        response = llm_client.complete(
            system_prompt=NOTEBOOK_DOMAIN_SPLITTER_SYSTEM_V1,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=2048,
        )
        try:
            result = json.loads(response.content)
            return result.get("domains", [])
        except json.JSONDecodeError:
            logger.warning("DomainSplitter returned non-JSON; using single domain.")
            all_tables = (
                [t["table_name"] for t in schema_plan.get("fact_tables", [])]
                + [t["table_name"] for t in schema_plan.get("dimension_tables", [])]
            )
            return [{"domain_name": "Main", "tables": all_tables, "description": "All tables"}]


class NotebookWriterAgent:
    """Generates a single PySpark notebook for one domain."""

    def run(
        self,
        domain: dict,
        schema_plan: dict,
        prior_notebook_cells: list | None = None,
    ) -> dict:
        """
        domain: {domain_name, tables, description}
        prior_notebook_cells: cell source strings from previous notebook (for context)
        Returns: {notebook_json, llm_response}
        """
        domain_name = domain["domain_name"]
        tables_list = ", ".join(domain.get("tables", []))

        # Extract only the relevant schema entries for this domain
        domain_tables = set(domain.get("tables", []))
        domain_schema = {
            "fact_tables": [
                t for t in schema_plan.get("fact_tables", [])
                if t["table_name"] in domain_tables
            ],
            "dimension_tables": [
                t for t in schema_plan.get("dimension_tables", [])
                if t["table_name"] in domain_tables
            ],
            "bridge_tables": [
                t for t in schema_plan.get("bridge_tables", [])
                if t.get("table_name") in domain_tables
            ],
        }

        # Build prior context (cell sources only, truncated to 3000 chars)
        if prior_notebook_cells:
            prior_context = "\n---\n".join(
                "".join(cell) if isinstance(cell, list) else cell
                for cell in prior_notebook_cells
            )[:3000]
            prior_context = f"Previous notebook cells (for reference):\n{prior_context}"
        else:
            prior_context = "This is the first notebook — no prior context."

        user_prompt = NOTEBOOK_WRITER_USER_V1.format(
            domain_name=domain_name,
            tables_list=tables_list,
            domain_schema_json=json.dumps(domain_schema, indent=2, default=str),
            prior_notebook_context=prior_context,
        )

        response = llm_client.complete(
            system_prompt=NOTEBOOK_WRITER_SYSTEM_V1,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=8192,
        )

        notebook_json = self._parse_notebook(response.content, domain_name)
        return {
            "notebook_json": notebook_json,
            "llm_response": response,
        }

    def _parse_notebook(self, content: str, domain_name: str) -> dict:
        cleaned = re.sub(r"^```(?:json)?\s*", "", content.strip(), flags=re.MULTILINE)
        cleaned = re.sub(r"\s*```$", "", cleaned.strip(), flags=re.MULTILINE)
        try:
            nb = json.loads(cleaned)
            # Ensure required notebook fields
            if "nbformat" not in nb:
                nb["nbformat"] = 4
            if "nbformat_minor" not in nb:
                nb["nbformat_minor"] = 5
            if "metadata" not in nb:
                nb["metadata"] = {
                    "kernelspec": {
                        "display_name": "PySpark",
                        "language": "python",
                        "name": "synapse_pyspark",
                    }
                }
            return nb
        except json.JSONDecodeError as e:
            logger.error(f"NotebookWriter parse error for {domain_name}: {e}")
            return _make_empty_notebook(domain_name)

    def get_cell_sources(self, notebook_json: dict) -> list[str]:
        """Extract cell source strings for use as prior context."""
        sources = []
        for cell in notebook_json.get("cells", []):
            src = cell.get("source", [])
            if isinstance(src, list):
                sources.append("".join(src))
            elif isinstance(src, str):
                sources.append(src)
        return sources


domain_splitter = NotebookDomainSplitter()
notebook_writer = NotebookWriterAgent()
