"""
Agent 6 — Notebook Writer (PySpark code generator).
Generates one Fabric PySpark notebook per domain cluster using medallion architecture.
LLM outputs clean PySpark code; backend wraps it in a .ipynb structure.
"""
from __future__ import annotations

import json
import logging
import re
import uuid

from app.core.azure_openai import LLMResponse, llm_client
from app.prompts import (
    NOTEBOOK_DOMAIN_SPLITTER_SYSTEM_V1,
    NOTEBOOK_DOMAIN_SPLITTER_USER_V1,
    NOTEBOOK_WRITER_SYSTEM_V1,
    NOTEBOOK_WRITER_USER_V1,
)

logger = logging.getLogger(__name__)


def _make_empty_notebook(domain_name: str) -> dict:
    """Returns a minimal valid .ipynb structure."""
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "PySpark",
                "language": "python",
                "name": "synapse_pyspark",
            },
            "language_info": {"name": "python"},
        },
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"# {domain_name} Domain — Microsoft Fabric Lakehouse Load\n\nAuto-generated by Schema Transformer."],
            }
        ],
    }


def _wrap_code_as_notebook(code: str, domain_name: str) -> dict:
    """Wraps raw PySpark code string into a valid .ipynb structure."""
    nb = _make_empty_notebook(domain_name)

    # Split code into logical sections at blank-line-separated blocks
    # and create one code cell per section for readability
    sections = re.split(r'\n{2,}(?=# ---)', code.strip())

    if not sections or not any(s.strip() for s in sections):
        return nb

    for section in sections:
        section = section.strip()
        if not section:
            continue
        nb["cells"].append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [section],
            "id": str(uuid.uuid4())[:8],
        })

    return nb


class NotebookDomainSplitter:
    """Clusters star schema tables into logical business domains."""

    def split(self, schema_plan: dict) -> list[dict]:
        """Returns list of domain dicts: {domain_name, tables, description}."""
        user_prompt = NOTEBOOK_DOMAIN_SPLITTER_USER_V1.format(
            schema_plan_json=json.dumps(schema_plan, indent=2, default=str)
        )
        response = llm_client.complete(
            system_prompt=NOTEBOOK_DOMAIN_SPLITTER_SYSTEM_V1,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=2048,
        )
        try:
            result = json.loads(response.content)
            return result.get("domains", [])
        except json.JSONDecodeError:
            logger.warning("DomainSplitter returned non-JSON; using single domain.")
            all_tables = (
                [t["table_name"] for t in schema_plan.get("fact_tables", [])]
                + [t["table_name"] for t in schema_plan.get("dimension_tables", [])]
                + [t.get("table_name", "") for t in schema_plan.get("bridge_tables", [])]
            )
            return [{"domain_name": "Main", "tables": [t for t in all_tables if t], "description": "All tables"}]


class NotebookWriterAgent:
    """Generates a single PySpark notebook for one domain."""

    def run(
        self,
        domain: dict,
        schema_plan: dict,
        current_relation_state: dict | None = None,
    ) -> dict:
        """
        domain: {domain_name, tables, description}
        schema_plan: full star schema plan from Agent 4
        current_relation_state: structured dict built by notebook_service after each domain
        Returns: {notebook_json, pyspark_code, llm_response}
        """
        domain_name = domain["domain_name"]
        tables_list = ", ".join(domain.get("tables", []))

        # Extract only the relevant schema entries for this domain
        domain_tables = set(domain.get("tables", []))
        domain_schema = {
            "fact_tables": [
                t for t in schema_plan.get("fact_tables", [])
                if t["table_name"] in domain_tables
            ],
            "dimension_tables": [
                t for t in schema_plan.get("dimension_tables", [])
                if t["table_name"] in domain_tables
            ],
            "bridge_tables": [
                t for t in schema_plan.get("bridge_tables", [])
                if t.get("table_name") in domain_tables
            ],
        }

        relation_state = current_relation_state or {
            "available_dataframes": [],
            "grain": "Unknown",
            "joined_tables": [],
            "primary_keys": [],
            "ready_for_join": list(domain_tables),
        }

        user_prompt = NOTEBOOK_WRITER_USER_V1.format(
            domain_name=domain_name,
            tables_list=tables_list,
            domain_schema_json=json.dumps(domain_schema, indent=2, default=str),
            current_relation_state_json=json.dumps(relation_state, indent=2, default=str),
        )

        response = llm_client.complete(
            system_prompt=NOTEBOOK_WRITER_SYSTEM_V1,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=8192,
        )

        pyspark_code = self._extract_code(response.content)
        notebook_json = _wrap_code_as_notebook(pyspark_code, domain_name)

        return {
            "notebook_json": notebook_json,
            "pyspark_code": pyspark_code,
            "llm_response": response,
        }

    def _extract_code(self, content: str) -> str:
        """Strip markdown fences and return clean Python code."""
        cleaned = re.sub(r"^```(?:python)?\s*", "", content.strip(), flags=re.MULTILINE)
        cleaned = re.sub(r"\s*```$", "", cleaned.strip(), flags=re.MULTILINE)
        return cleaned.strip()

    def get_cell_sources(self, notebook_json: dict) -> list[str]:
        """Extract cell source strings (kept for backward compat if needed)."""
        sources = []
        for cell in notebook_json.get("cells", []):
            src = cell.get("source", [])
            if isinstance(src, list):
                sources.append("".join(src))
            elif isinstance(src, str):
                sources.append(src)
        return sources


domain_splitter = NotebookDomainSplitter()
notebook_writer = NotebookWriterAgent()
